#!/usr/bin/env python
"""Fake OpenWiki CLI used by the test suite.

Creates a minimal ``openwiki/`` directory in the current working directory so
the whole service pipeline (fetch -> run -> pack -> download) can be tested end
to end without a model provider or network access.
"""

from __future__ import annotations

import json
import os
import sys
import time
from pathlib import Path

#: Environment variables recorded in openwiki/.fake-env.json for test assertions.
DUMPED_ENV_KEYS = (
    "OPENAI_COMPATIBLE_BASE_URL",
    "OPENWIKI_PAGE_CONCURRENCY",
    "OPENWIKI_PROVIDER",
)


def main() -> int:
    if os.environ.get("FAKE_OPENWIKI_FAIL"):
        print("error: simulated provider failure", file=sys.stderr)
        return 2

    sleep_seconds = float(os.environ.get("FAKE_OPENWIKI_SLEEP", "0") or 0)
    if sleep_seconds:
        time.sleep(sleep_seconds)

    wiki = Path.cwd() / "openwiki"
    (wiki / ".claims").mkdir(parents=True, exist_ok=True)
    (wiki / ".claims" / "quickstart.json").write_text(
        '{"schemaVersion": 1, "pageVersion": "sha256:test", "claims": []}',
        encoding="utf-8",
    )
    (wiki / ".fake-args.json").write_text(json.dumps(sys.argv[1:]), encoding="utf-8")
    (wiki / ".fake-env.json").write_text(
        json.dumps({key: os.environ.get(key) for key in DUMPED_ENV_KEYS}, indent=2),
        encoding="utf-8",
    )
    (wiki / "index.md").write_text(
        '---\ntype: index\nokf_version: "0.2"\n---\n\n# Sample wiki\n\n- [Architecture](architecture.md)\n',
        encoding="utf-8",
    )
    print("openwiki: page 1/2 index.md", flush=True)
    (wiki / "architecture.md").write_text(
        "---\ntype: concept\n---\n\n# Architecture\n\nGenerated by the fake CLI.\n",
        encoding="utf-8",
    )
    print("openwiki: page 2/2 architecture.md", flush=True)
    last_update: dict[str, object] = {
        "command": "init" if "--init" in sys.argv else "update",
        "status": "complete",
    }
    if os.environ.get("FAKE_OPENWIKI_GITHEAD"):
        import subprocess

        last_update["gitHead"] = subprocess.run(
            ["git", "rev-parse", "HEAD"], capture_output=True, text=True, check=False
        ).stdout.strip()
    (wiki / ".last-update.json").write_text(json.dumps(last_update), encoding="utf-8")
    print("openwiki: run complete", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
